pg version support and doc changes

diff --git a/tools/mkdevsitters b/tools/mkdevsitters
--- a/tools/mkdevsitters
+++ b/tools/mkdevsitters
@@ -12,6 +12,7 @@ mds_mksitterconfig="$mds_basedir/tools/mksitterconfig"
 mds_ip="$1"
 mds_zkconnstr="$2"
 mds_shard="$3"
+mds_pgversion="$4"
 
 function fail
 {
@@ -29,6 +30,7 @@ function mksitter
 	ip="$2"
 	zkconnstr="$3"
 	shard="$4"
+        pgversion="$5"
 	dataset="zones/$mds_zonename/data/peer$which"
 	sitterdir="$PWD/devconfs/sitter$which"
 	mountpoint="$PWD/devconfs/datasets/manatee$which"
@@ -63,13 +65,14 @@ function mksitter
 	#
 	mkdir -p $sitterdir
 	mkdir -p $sitterdir/9.2
+	mkdir -p $sitterdir/9.6
 	mkdir -p $sitterdir/log
 	chown postgres:postgres $sitterdir/log || \
 	    fail "failed to chown postgres log directory"
 
 	echo -n "peer $which: creating configuration ... "
 	$mds_mksitterconfig "$PWD/devconfs" "$ip" "$zkconnstr" "$which" \
-	    "$shard" > "$sitterdir/sitter.json" || fail "failed"
+	    "$shard" "$pgversion" > "$sitterdir/sitter.json" || fail "failed"
 	echo "{}" > "$sitterdir/pg_overrides.json" || fail "failed"
 	echo "done."
 
@@ -80,12 +83,12 @@ function mksitter
 
 	echo -n "peer $which: creating template postgresql.conf ... "
 	egrep -v '^\s*port\s*=' "$mds_basedir/etc/postgresql.conf" |
-	    egrep -v '^\s*log_directory\s*=' > "$sitterdir/9.2/postgresql.conf"
+	    egrep -v '^\s*log_directory\s*=' > "$sitterdir/9.6/postgresql.conf"
 	echo "port = $port # (change requires restart)" >> \
-	    "$sitterdir/9.2/postgresql.conf"
-	echo "log_directory = '$sitterdir/log'" >> "$sitterdir/9.2/postgresql.conf"
+	    "$sitterdir/$pgversion/postgresql.conf"
+	echo "log_directory = '$sitterdir/log'" >> "$sitterdir/$pgversion/postgresql.conf"
 	for conf in recovery pg_hba; do
-		cp "$mds_basedir/etc/$conf.conf" "$sitterdir/9.2/."
+		cp "$mds_basedir/etc/$conf.conf" "$sitterdir/$pgversion/."
 	done
 	echo "done."
 
@@ -106,12 +109,20 @@ if ! type zonename > /dev/null 2>&1; then
 	fail "cannot determine dataset root: zonename(1M) command not found"
 fi
 
-if [[ $# -ne 3 ]]; then
-	echo "usage: $mds_arg0 LOCAL_IP ZK_IP:ZK_PORT SHARD" >&2
+if [[ $# -lt 3 ]]; then
+	echo "usage: $mds_arg0 LOCAL_IP ZK_IP:ZK_PORT SHARD PG_VERSION" >&2
 	exit 2
+fi
+
+if [[ -z "$mds_pgversion" ]]; then
+    mds_pgversion="9.6"
+fi
+
+if [[ "$mds_pgversion" != "9.2" ]] && [[ "$mds_pgversion" != "9.6" ]]; then
+    fail "supported version are \"9.2\" or \"9.6\""
 fi
 
 mds_zonename="$(zonename)"
 for (( i = 1; i <= 3; i++ )) {
-	mksitter $i "$mds_ip" "$mds_zkconnstr" "$mds_shard"
+	mksitter $i "$mds_ip" "$mds_zkconnstr" "$mds_shard" "$mds_pgversion"
 }
